Trying to fix bug
Part 5 - https://youtu.be/x8B_eXfcj6U?t=601

https://github.com/acord-robotics/unity-intro/issues/21

Curl error 56: Receiving data failed with unitytls error code 1048578
Assets\Scripts\Monsters\Pokemon.cs(35,45): error CS1061: 'PokemonBase' does not contain a definition for 'MaxHp' and no accessible extension method 'MaxHp' accepting a first argument of type 'PokemonBase' could be found (are you missing a using directive or an assembly reference?)